# Generated by Django 4.2 on 2023-04-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0003_alter_departamento_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departamento",
            options={
                "ordering": ["name"],
                "verbose_name": "Mi Departamento",
                "verbose_name_plural": "Areas de la empresa",
            },
        ),
    ]
