# Generated by Django 4.2 on 2023-04-24 16:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0003_empleado_habilidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="hoja_de_vida",
            field=ckeditor.fields.RichTextField(default="Texto de ejemplo"),
            preserve_default=False,
        ),
    ]
