# Generated by Django 4.2 on 2023-04-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0004_empleado_hoja_de_vida"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Nombre Completo"
            ),
        ),
    ]
