# Generated by Django 4.2 on 2023-04-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0002_habilidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="habilidades",
            field=models.ManyToManyField(to="persona.habilidades"),
        ),
    ]
